version: '3.3'
services:

  ####################################################################################
  ####################################################################################
  ###### SWARMPIT MONITORING
  ####################################################################################
  ####################################################################################

version: '3.2'

services:

  ################################################################################
  ################################################################################
  ##### TRAEFIK AS A HTTPS LOAD BALANCER
  ################################################################################
  ################################################################################
  ##### 
  ##### Alternative entrypoints:
  ##### ------------------------
  #####
  ##### Disable HTTP to HTTPS auto redirection:
  ##### --entrypoints=Name:http Address::80
  #####
  ##### Force SSL certificate
  ##### --entrypoints=Name:https Address::443 TLS:/path/certif.pem,/path/certif.key
  ##### 
  ################################################################################

  proxy:
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=${PROXY_ACME_EMAIL}"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--logLevel=DEBUG"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.network=traefiked"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.domain=${HOST_ROOT_DOMAIN}"
      - "--docker.watch"
      - "--web.metrics.datadog=true"
      - "--web.metrics.datadog.address=datadog-agent:8125"
    networks:
      - traefiked
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - traefik_data:/etc/traefik/acme
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "traefik.basic.port=8080"
        - "traefik.basic.protocol=http"
        - "traefik.basic.frontend.rule=Host:${TRAEFIK_DASHBOARD_HOST}"
        - "traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH}"
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

################################################################################
################################################################################
##### NEEDED EXTERNAL OVERLAY NETWORKS
################################################################################
################################################################################

networks:
  traefiked:
    external:
      name: traefiked

volumes:
  traefik_data:
    driver: local